name: First Workflow

on: push 
jobs: 
    build: 
      run-ons: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - name: Runs a simple Github action
        - run: echo "This woorkflow runs  successfully for this  particular action"

        -name: Simulating error 
        run: echo "Error taking place"; exit 1
